CC = g++

CFLAGS = -I/usr/local/include/opencv -I/usr/local/include -L/usr/local/lib -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn -lopencv_dpm -lopencv_fuzzy -lopencv_line_descriptor -lopencv_optflow -lopencv_plot -lopencv_reg -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_rgbd -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_face -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_flann -lopencv_xobjdetect -lopencv_objdetect -lopencv_ml -lopencv_xphoto -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_photo -lopencv_imgproc -lopencv_core

cv2-capture:
	$(CC) $(CFLAGS) -o cv2-capture cv2-capture.cpp

cv2-convert-to-gray:
	$(CC) $(CFLAGS) -o cv2-convert-to-gray cv2-convert-to-gray.cpp

cv2-mat:
	$(CC) $(CFLAGS) -o cv2-mat cv2-mat.cpp

cv2-mat2:
	$(CC) $(CFLAGS) -o cv2-mat2 cv2-mat2.cpp

