CC = g++

CFLAGS = -I/usr/local/include/opencv -I/usr/local/include -L/usr/local/lib -lopencv_highgui -lopencv_videoio -lopencv_imgproc -lopencv_core

cv2-capture:
	$(CC) $(CFLAGS) -o cv2-capture cv2-capture.cpp

cv2-convert-to-gray:
	$(CC) $(CFLAGS) -o cv2-convert-to-gray cv2-convert-to-gray.cpp

cv2-mat:
	$(CC) $(CFLAGS) -o cv2-mat cv2-mat.cpp

cv2-mat2:
	$(CC) $(CFLAGS) -o cv2-mat2 cv2-mat2.cpp

